name: Run Locust Tests on Commit

on:
  push:
    branches:
      - main

jobs:
  locust-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install locust

      - name: Start Flask server
        run: |
          python server.py &
          echo "Waiting for Flask server to start..."
          sleep 10

      - name: Run Locust load tests
        run: |
          mkdir locust_results
          locust -f locustfile.py --headless -u 10000 -r 100 --run-time 2m --host=http://localhost:5000 --csv=locust_results/result

      - name: Archive Locust results
        uses: actions/upload-artifact@v3
        with:
          name: locust-results
          path: locust_results/
