name: Run Locust Tests on Commit

on:
  push:
    branches:
      - main

jobs:
  locust-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask locust

      - name: Start Flask server
        run: |
          python server.py &
          echo "Waiting for Flask server to start"
          sleep 30

      - name: Run Locust load test (10K users, ramp-up 100/s, 2 mins)
        run: |
          locust -f locustfile.py --headless --host=http://localhost:5000 \
            --users 10000 --spawn-rate 100 --run-time 2m \
            --csv=locust_stats

      - name: Archive Locust results
        uses: actions/upload-artifact@v3
        with:
          name: locust-results
          path: |
            locust_stats_stats.csv
            locust_stats_failures.csv
            locust_stats_distribution.csv
